# Generated by Django 5.0.4 on 2024-05-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrested',
            name='event',
        ),
        migrations.DeleteModel(
            name='Evenement',
        ),
    ]
