# Generated by Django 5.0.4 on 2024-05-17 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0002_remove_intrested_event_delete_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('contact_Event', models.CharField(max_length=255)),
                ('date_enev', models.DateField()),
                ('heure_deb', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('place_dispo', models.IntegerField()),
                ('img', models.ImageField(blank=True, upload_to='event_photos')),
                ('price', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intrested',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='isety.evenement'),
            preserve_default=False,
        ),
    ]
