# Generated by Django 5.0.4 on 2024-05-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0003_evenement_intrested_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrested',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_intrest', to='isety.evenement'),
        ),
    ]
