# Generated by Django 5.0.4 on 2024-05-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0004_alter_intrested_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='inrest',
            field=models.IntegerField(default=0),
        ),
    ]
