# Generated by Django 5.0.4 on 2024-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0008_user_friends_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('intrested', 'Intrested'), ('friend_request', 'friend request')], default='', max_length=20),
        ),
    ]
