# Generated by Django 5.0.4 on 2024-05-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
