# Generated by Django 5.0.4 on 2024-05-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isety', '0010_friend_request_is_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend_Request',
        ),
    ]
